### ISSUE TITLE
Docker/DB uses server's environment variables

### ISSUE THREAD

**Issue by aurelenc** [TEAM-AAAAAAAAAAAAAAAA/AREA#83]
```bash
aurele@arcaurele ~/Delivery/AREA (main) [14]> docker-compose up db
open /home/aurele/Delivery/AREA/server/.env/.env.dev: no such file or directory
```

How to reproduce:
Remove the server's .env files or folder

Works as expected only if the server's environment variables are the same as the DB but it might not be the case everytime

**Comment by Cavonstavant** [comment]
Even though you are only starting the `db` service, docker-compose will still look to validate the docker-compose.yml. This means docker-compose will check the existence of the `server/.env/.env.dev` even when starting the db service.

**Comment by aurelenc** [comment]
this is not a fix this is a workaround

**Comment by Cavonstavant** [comment]
docker-compose works like that. I encourage you to open an issue or a pull request to this repo [https://github.com/docker/compose](https://github.com/docker/compose) if you find this behavior not appropriate

**Comment by aurelenc** [comment]
this is bad but ok
